openapi: 3.0.3
info:
  title: Swagger Canban - OpenAPI 3.0
  version: '1'
tags:
  - name: user
    description: Operations about user
paths:
#  USERS
  /users:
    $ref: './entities/users/paths/users.yaml'
  /users/profile:
    $ref: './entities/users/paths/users-profile.yaml'
  /users/search:
    $ref: './entities/users/paths/users-search.yaml'
  /users/participants/{dashboardId}:
    $ref: './entities/users/paths/users-participants-{dashboardId}.yaml'
  /users/registration:
    $ref: './entities/users/paths/users-registration.yaml'
  /users/join:
    $ref: './entities/users/paths/users-join.yaml'
  /users/remove-from-dashboard:
    $ref: './entities/users/paths/users-remove-from-dashboard.yaml'

  #    DASHBOARDS
  /dashboards:
    $ref: './entities/dashboards/paths/dashboards.yaml'
  /dashboards/{dashboardId}:
    $ref: './entities/dashboards/paths/dashboards-{dashboardId}.yaml'

  # COLUMNS
  /columns:
    $ref: './entities/columns/path/columns.yaml'