openapi: 3.0.3
info:
  title: Swagger Canban - OpenAPI 3.0
  version: '1'
tags:
  - name: user
    description: Operations about user
paths:
#  USERS
  /users:
    $ref: './entities/users/paths/users.yaml'
  /users/profile:
    $ref: './entities/users/paths/users-profile.yaml'
  /users/search:
    $ref: './entities/users/paths/users-search.yaml'
  /users/participants/{dashboardId}:
    $ref: './entities/users/paths/users-participants-{dashboardId}.yaml'
  /users/registration:
    $ref: './entities/users/paths/users-registration.yaml'
  /users/join:
    $ref: './entities/users/paths/users-join.yaml'
  /users/remove-from-dashboard:
    $ref: './entities/users/paths/users-remove-from-dashboard.yaml'

  #    DASHBOARDS
  /dashboards:
    $ref: './entities/dashboards/paths/dashboards.yaml'
  /dashboards/{dashboardId}:
    $ref: './entities/dashboards/paths/dashboards-{dashboardId}.yaml'

  # COLUMNS
  /columns:
    $ref: './entities/columns/path/columns.yaml'
  /columns/{dashboardId}:
    $ref: './entities/columns/path/columns-{dashboardId}.yaml'

# TODOS
  /todos:
    $ref: './entities/todos/path/todos.yaml'
  /todos/{todoId}:
    $ref: './entities/todos/path/todos-{todoId}.yaml'
  /todos/{columnId}:
    $ref: './entities/todos/path/todos-{columnId}.yaml'
  /todos/detail/{todoId}:
    $ref: './entities/todos/path/todos-detail.yaml'
  /todos/move-todo:
    $ref: './entities/todos/path/todos-move-todo.yaml'

# COMMENTS
  /comments:
    $ref: './entities/comments/path/comments.yaml'
  /comments/{todoId}:
    $ref: './entities/comments/path/comments-{todoId}.yaml'
  /comments/{commentId}:
    $ref: './entities/comments/path/comments-{commentId}.yaml'
  /comments/detail/{commentId}:
    $ref: './entities/comments/path/comments-detail-{commentsId}.yaml'

# NOTIFICATIONS
#  /notifications:
#    $ref: './entities/notifications/paths/notifications.yaml'

